coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 85%
        threshold: 5%

ignore:
  - "**/*Test*"
  - "**/test/**"
  - "**/androidTest/**"
  - "**/commonTest/**"
  - "**/iosTest/**"
  - "**/build/**"
  - "**/R.class"
  - "**/R$*.class"
  - "**/BuildConfig.*"
  - "**/Manifest*.*"
  - "**/databinding/*"
  - "**/android/databinding/*"
  - "**/androidx/databinding/*"
  - "**/BR.*"
  - "**/presentation/ui/components/**"
  - "**/presentation/ui/screens/**"
  - "**/*Kt.class"
  - "**/*$Companion.class"
  - "**/ComposableSingletons*.*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true
