coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        base: auto
        branches:
          - develop
          - main
    patch:
      default:
        target: 85%
        threshold: 5%
        branches:
          - develop
          - main

# Configure which branch to use for the badge
codecov:
  branch: develop
  
# Configure GitHub checks and annotations
github_checks:
  annotations: true

# Force Codecov to process reports even with small changes  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "**/*Test*"
  - "**/test/**"
  - "**/androidTest/**"
  - "**/commonTest/**"
  - "**/iosTest/**"
  - "**/build/**"
  - "**/R.class"
  - "**/R$*.class"
  - "**/BuildConfig.*"
  - "**/Manifest*.*"
  - "**/databinding/*"
  - "**/android/databinding/*"
  - "**/androidx/databinding/*"
  - "**/BR.*"
  - "**/presentation/ui/components/**"
  - "**/presentation/ui/screens/**"
  - "**/*Kt.class"
  - "**/*$Companion.class"
  - "**/ComposableSingletons*.*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
