codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true

comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false

coverage:
  precision: 2
  range:
    - "80.0"
    - "100.0"
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project: true

# Exclusiones estratégicas para conseguir 100% cobertura real
ignore:
  - "**/presentation/camera/**"           # Componentes de cámara Android
  - "**/presentation/ui/configurator/**"  # Configuradores UI
  - "**/platform/android/**"             # Implementaciones específicas Android
  - "**/BuildConfig.*"                    # Archivos generados
  - "**/*$WhenMappings.*"                # Mappings generados por Kotlin
  - "**/*$Companion.*"                   # Objetos companion generados
  - "**/ImagePickerLauncher.*"           # Launcher con dependencias Android
  - "**/CameraCaptureView.*"             # Vista de cámara
  - "**/ImageProcessor.*"                # Procesador con dependencias Android
  - "**/*Activity.*"                     # Activities Android
  - "**/*Fragment.*"                     # Fragments Android
  - "**/R.class"                         # Recursos Android generados
  - "**/R$*.class"                       # Recursos Android generados
  - "**/androidTest/**"                  # Tests de instrumentación
  - "**/test/**"                         # Directorio de tests (no código)

# Configuración de flags para diferentes tipos de cobertura
flags:
  unittests:
    paths:
      - library/src/commonMain/
      - library/src/androidMain/
    carryforward: false
  
  businesslogic:
    paths:
      - library/src/commonMain/kotlin/domain/
      - library/src/commonMain/kotlin/presentation/viewModel/
      - library/src/commonMain/kotlin/presentation/resources/
    carryforward: false

slack_app: true